config {
    dependencies: ["trusted-oms_courier_type_cev", "trusted-oms_courier_type_lb"],
    tags: ["cubo-vendas", "oms"]
}

TRUNCATE TABLE REFINED.COURIER_TYPE;

INSERT INTO 
    REFINED.COURIER_TYPE (
SELECT
  id,
  type,
  "CEV" AS BANDEIRA,
  CURRENT_TIMESTAMP() AS DATA_ATUALIZACAO
FROM `TRUSTED.oms_courier_type_cev`

UNION ALL

SELECT
  id,
  type,
  "LB" AS BANDEIRA,
  CURRENT_TIMESTAMP() AS DATA_ATUALIZACAO
FROM `TRUSTED.oms_courier_type_lb` )