config {
    dependencies: ["trusted-oms_order_type_cev", "trusted-oms_order_type_lb"],
    tags: ["cubo-vendas", "oms", "oms-full"]
}

TRUNCATE TABLE REFINED.ORDER_TYPE;

INSERT INTO
    REFINED.ORDER_TYPE (
SELECT
  id,
  name,
  "CEV" AS BANDEIRA,
  CURRENT_TIMESTAMP() AS DATA_ATUALIZACAO
FROM `TRUSTED.oms_order_type_cev`

UNION ALL

SELECT
  id,
  name,
  "LB" AS BANDEIRA,
  CURRENT_TIMESTAMP() AS DATA_ATUALIZACAO
FROM `TRUSTED.oms_order_type_lb`
    )